name: soko64_web
description: An absolute bare-bones web app.
version: 1.0.0
repository: 

environment:
  sdk: ^3.7.3

# Add regular dependencies here.
dependencies:
  web: ^1.1.1
  bullseye2d: ^1.0.9
  collection: ^1.19.1
  vector_math: ^2.2.0

dev_dependencies:
  build_runner: ^2.4.8
  build_web_compilers: ^4.0.9
  lints: ^5.0.0
